#!/bin/bash

if [ -d .git/rebase-apply ] || [ -d .git/rebase-merge ]; then
  git rebase --abort
elif [ -f .git/MERGE_HEAD ]; then
  git merge --abort
elif [ -f .git/CHERRY_PICK_HEAD ]; then
  git cherry-pick --abort
elif [ -f .git/REVERT_HEAD ]; then
  git revert --abort
else
  echo "Nothing to abort."
fi
